"""Stable identifiers for in-app notifications (rendered with {% trans %} in templates)."""

PROFILE_CHANGE_PENDING = "profile_change_pending"
PROFILE_CHANGE_APPROVED = "profile_change_approved"
PROFILE_CHANGE_REJECTED = "profile_change_rejected"
TEACHER_PREFERENCE_PENDING = "teacher_preference_pending"
TEACHER_PREFERENCE_APPROVED = "teacher_preference_approved"
TEACHER_PREFERENCE_REJECTED = "teacher_preference_rejected"
DEMO_SEEDED = "demo_seeded"
DEMO_SCHEDULE_REMINDER = "demo_schedule_reminder"
DEMO_SCHEDULE_AVAILABLE = "demo_schedule_available"
SCHEDULE_UPDATED = "schedule_updated"
