# Generated by Django 5.1.6 on 2026-03-17 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_per_week', models.PositiveIntegerField(default=1)),
                ('min_room_capacity', models.PositiveIntegerField(default=0)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='university.discipline')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='university.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='university.teacherprofile')),
            ],
            options={
                'verbose_name': 'Teaching requirement',
                'verbose_name_plural': 'Teaching requirements',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#58B2FF', max_length=16)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='university.discipline')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='university.group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='university.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='university.teacherprofile')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='university.timeslot')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['timeslot__day_of_week', 'timeslot__period'],
                'unique_together': {('group', 'timeslot'), ('room', 'timeslot'), ('teacher', 'timeslot')},
            },
        ),
    ]
