# Generated by Django 5.1.6 on 2026-03-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('generate', 'Generate'), ('optimize', 'Optimize')], max_length=16)),
                ('ok', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Algorithm run log',
                'verbose_name_plural': 'Algorithm run logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='If enabled, this lesson will not be changed by automatic algorithms.'),
        ),
    ]
