# Generated by Django 5.2.12 on 2026-03-26 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_algorithmrunlog_lesson_is_frozen'),
        ('university', '0006_organization_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('publish', 'Publish'), ('generate', 'Generate')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lesson change log',
                'verbose_name_plural': 'Lesson change logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Draft lessons are hidden from students until published.', verbose_name='Draft'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published at'),
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(max_length=64, verbose_name='Slug')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('is_current', models.BooleanField(default=False, help_text='Used as default when no period is selected in the session.', verbose_name='Current period')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_periods', to='university.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Academic period',
                'verbose_name_plural': 'Academic periods',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='academic_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='scheduling.academicperiod', verbose_name='Academic period'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('group', 'timeslot', 'academic_period'), name='uniq_lesson_group_slot_period'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('teacher', 'timeslot', 'academic_period'), name='uniq_lesson_teacher_slot_period'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('room', 'timeslot', 'academic_period'), name='uniq_lesson_room_slot_period'),
        ),
        migrations.AddField(
            model_name='lessonchangelog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_change_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonchangelog',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='scheduling.lesson'),
        ),
        migrations.AddConstraint(
            model_name='academicperiod',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uniq_academic_period_org_slug'),
        ),
    ]
