# Generated by Django 5.2.12 on 2026-03-27 17:48

import django.db.models.deletion
from django.db import migrations, models


def backfill_algorithmrunlog_organization(apps, schema_editor):
    AlgorithmRunLog = apps.get_model("scheduling", "AlgorithmRunLog")
    Organization = apps.get_model("university", "Organization")
    for log in AlgorithmRunLog.objects.all().iterator(chunk_size=500):
        if log.organization_id:
            continue
        details = log.details or {}
        if not isinstance(details, dict):
            continue
        oid = details.get("organization_id")
        if oid and Organization.objects.filter(pk=oid).exists():
            log.organization_id = oid
            log.save(update_fields=["organization_id"])


def noop_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_lesson_academic_period_required'),
        ('university', '0006_organization_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmrunlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='algorithm_run_logs', to='university.organization', verbose_name='Organization'),
        ),
        migrations.RunPython(backfill_algorithmrunlog_organization, noop_backfill),
    ]
