# Generated by Django 5.2.12 on 2026-03-27 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_algorithmrunlog_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPreferenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_preferred_days', models.JSONField(blank=True, default=list, verbose_name='Preferred days')),
                ('proposed_preferred_periods', models.JSONField(blank=True, default=list, verbose_name='Preferred periods')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection reason')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_teacher_preference_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_preference_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher preference request',
                'verbose_name_plural': 'Teacher preference requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='scheduling__user_id_fb4b4c_idx')],
            },
        ),
    ]
