# Generated by Django 5.2.12 on 2026-03-28 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_teacher_preference_request'),
        ('university', '0006_organization_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotPedagogicalFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_fatigue_index', models.FloatField(default=0.5, help_text='0 = low reported fatigue, 1 = high (questionnaires / self-report).', verbose_name='Student fatigue index')),
                ('survey_burden_index', models.FloatField(default=0.5, help_text='0 = slot feels light, 1 = students rate it as overloaded / stressful.', verbose_name='Survey burden index')),
                ('lms_activity_normalized', models.FloatField(default=0.5, help_text='0..1 relative engagement vs other slots (logins, submissions).', verbose_name='LMS activity (normalized)')),
                ('historical_semester_load', models.FloatField(default=0.5, help_text='0..1 from past timetables: how often this slot was heavily used.', verbose_name='Historical semester load')),
                ('target_unfitness_label', models.FloatField(blank=True, help_text='Optional 0..1 label for training: high = avoid placing important lessons here.', null=True, verbose_name='Target unfitness (supervised label)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_pedagogical_features', to='university.organization', verbose_name='Organization')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogical_features', to='university.timeslot', verbose_name='Time slot')),
            ],
            options={
                'verbose_name': 'Slot pedagogical features',
                'verbose_name_plural': 'Slot pedagogical features',
                'constraints': [models.UniqueConstraint(fields=('organization', 'timeslot'), name='uniq_slot_pedagogical_features_org_slot')],
            },
        ),
    ]
