"""Compatibility shim — use ``from scheduling.ml.predict import ...``."""

from scheduling.ml.predict import (  # noqa: F401
    FEATURE_KEYS,
    FEATURE_SIZE,
    ML_PENALTY_SCALE,
    apply_student_schedule_biases,
    clear_model_cache,
    dashboard_ml_series,
    explainability_ablation,
    explanation_sentence,
    feature_vector,
    feature_vector_from_row,
    heuristic_from_vector,
    heuristic_unfitness,
    keras_model_available,
    ml_penalty_units,
    model_file_path,
    neural_vs_heuristic_series,
    predict_from_vector,
    predict_slot_unfitness,
    predict_slot_unfitness_for_student,
    prediction_backend_label,
    slot_insights_for_organization,
    try_shap_for_slot,
)
