# Generated by Django 5.2.12 on 2026-03-26 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verbose_name_labels'),
        ('university', '0004_organization_multitenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='university.organization', verbose_name='Organization'),
        ),
    ]
