# Generated by Django 5.2.12 on 2026-03-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_change_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='profile_change_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.profilechangerequest'),
        ),
    ]
