# Generated by Django 5.2.12 on 2026-03-27 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification_kind_payload'),
        ('scheduling', '0007_teacher_preference_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='teacher_preference_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='scheduling.teacherpreferencerequest'),
        ),
    ]
