# Generated by Django 5.2.12 on 2026-03-26 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_room_equipment_room_floor_room_room_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplines', to='university.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='university.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='size',
            field=models.PositiveIntegerField(default=25, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, max_length=120, verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=30, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='equipment',
            field=models.TextField(blank=True, verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='Room type'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course_year',
            field=models.PositiveIntegerField(default=1, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='university.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='academic_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Academic title'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='university.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Experience (years)'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='office_room',
            field=models.CharField(blank=True, max_length=120, verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='preferred_days',
            field=models.JSONField(blank=True, default=list, verbose_name='Preferred days'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='preferred_periods',
            field=models.JSONField(blank=True, default=list, verbose_name='Preferred periods'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=120, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
