# Generated by Django 5.2.12 on 2026-03-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_organization_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='schedule_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Optional weights for personalized slot scoring: fatigue_sensitivity, survey_sensitivity, prefer_morning (0..1).', verbose_name='Schedule / ML preferences'),
        ),
    ]
